services:
  billing-db:
    image: postgres:16.1
    container_name: billing-db

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: billing-db
      POSTGRES_USER: billing
      POSTGRES_PASSWORD: billing

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d billing-db" ]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - billing-db-data:/var/lib/postgresql/data

volumes:
  billing-db-data:
